name: Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: Update package index
        run: sudo apt-get update
      - name: Install mpi libs
        run: sudo apt-get -y install libopenmpi-dev
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Coverage Part 1
        run: tox -e cov1 || true
      - name: Run Coverage Part 2
        run: tox -e cov2,report
      - name: Upload Coverage Part 3
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

